# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: CoursePlatform
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: