app:
  port: ":4040"

db:
  user: "myuser"
  password: "mypassword"
  ip: "db"  # This should be the name of the database service in your docker-compose.yml
  port: 5432
  name: "CoursePlatform"
  active: false

neo4j:
    user: "neo4j"
    password: "mypassword
    uri: "neo4j://neo4j:7687"
    port: 7687
    active: true
