app:
  port: "4040"

db:
  user: "myuser"
  password: "mypassword"
  ip: "localhost"  # This should be the name of the database service in your docker-compose.yml
  port: 5432
  name: "CoursePlatform"
  active: true
